# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2022-03-26 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0002_permission_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='权限名称'),
        ),
    ]
