# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2022-03-26 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0003_auto_20220326_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='level',
            field=models.IntegerField(default=0, verbose_name='会员等级'),
        ),
    ]
